<a href="https://colab.research.google.com/github/shannonmalach/Geospatial_Python_Projects/blob/main/Educational_Attainment_SVI_Community_Health.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Geospatial Analysis of Educational Attainment, Social Vulnerability & Community Health Indicators

##### Shannon Malach

#### Loading the data

In [ ]:
# importing pandas into python
import pandas as pd

# importing the datasets
from google.colab import files
uploaded = files.upload()

Saving HCAQ&P Downloaded Table.csv to HCAQ&P Downloaded Table.csv
Saving SCC&SVI Downloaded Table.csv to SCC&SVI Downloaded Table.csv

In [ ]:
# importing csv files
hc_access_quality = pd.read_csv('HCAQ&P Downloaded Table.csv')

# viewing the dataframe
hc_access_quality

,Year,Domain,Measure,GEOID,Tract,County,State,Value
0,2020,Health Care Access and Quality,Percent current on preventive services (65+),51001090102,Census Tract 901.02,Accomack,VA,51.700000
1,2020,Health Care Access and Quality,Percent current on preventive services (65+),51001090201,Census Tract 902.01,Accomack,VA,47.550000
2,2020,Health Care Access and Quality,Percent current on preventive services (65+),51001090202,Census Tract 902.02,Accomack,VA,47.549997
3,2020,Health Care Access and Quality,Percent current on preventive services (65+),51001090300,Census Tract 903,Accomack,VA,43.049997
4,2020,Health Care Access and Quality,Percent current on preventive services (65+),51001090401,Census Tract 904.01,Accomack,VA,38.150000
...,...,...,...,...,...,...,...,...
2169,2020,Health Care Access and Quality,Percent current on preventive services (65+),51840000102,Census Tract 1.02,Winchester City,VA,38.550000
2170,2020,Health Care Access and Quality,Percent current on preventive services (65+),51840000201,Census Tract 2.01,Winchester City,VA,47.488372
2171,2020,Health Care Access and Quality,Percent current on preventive services (65+),51840000202,Census Tract 2.02,Winchester City,VA,51.800000
2172,2020,Health Care Access and Quality,Percent current on preventive services (65+),51840000301,Census Tract 3.01,Winchester City,VA,40.911930
2173,2020,Health Care Access and Quality,Percent current on preventive services (65+),51840000302,Census Tract 3.02,Winchester City,VA,45.099997

In [ ]:
# important csv files
context_svi = pd.read_csv('SCC&SVI Downloaded Table.csv')

# viewing the dataframe
context_svi

,Year,Domain,Measure,GEOID,Tract,County,State,Value
0,2020,Social and Community Context,Social Vulnerability Index (SVI),51001090102,Census Tract 901.02,Accomack,VA,0.6348
1,2020,Social and Community Context,Social Vulnerability Index (SVI),51001090201,Census Tract 902.01,Accomack,VA,0.2858
2,2020,Social and Community Context,Social Vulnerability Index (SVI),51001090202,Census Tract 902.02,Accomack,VA,0.5158
3,2020,Social and Community Context,Social Vulnerability Index (SVI),51001090300,Census Tract 903,Accomack,VA,0.6387
4,2020,Social and Community Context,Social Vulnerability Index (SVI),51001090401,Census Tract 904.01,Accomack,VA,0.8315
...,...,...,...,...,...,...,...,...
2180,2020,Social and Community Context,Social Vulnerability Index (SVI),51840000102,Census Tract 1.02,Winchester City,VA,0.9573
2181,2020,Social and Community Context,Social Vulnerability Index (SVI),51840000201,Census Tract 2.01,Winchester City,VA,0.6220
2182,2020,Social and Community Context,Social Vulnerability Index (SVI),51840000202,Census Tract 2.02,Winchester City,VA,0.2283
2183,2020,Social and Community Context,Social Vulnerability Index (SVI),51840000301,Census Tract 3.01,Winchester City,VA,0.8226
2184,2020,Social and Community Context,Social Vulnerability Index (SVI),51840000302,Census Tract 3.02,Winchester City,VA,0.7642

In [ ]:
# renaming the value columns in each dateframe
hc_access_quality = hc_access_quality.rename(columns={"Value": "SV_index"})
context_svi = context_svi.rename(columns={"Value": "pct_services"})

,Year,Domain,Measure,GEOID,Tract,County,State,pct_services
0,2020,Social and Community Context,Social Vulnerability Index (SVI),51001090102,Census Tract 901.02,Accomack,VA,0.6348
1,2020,Social and Community Context,Social Vulnerability Index (SVI),51001090201,Census Tract 902.01,Accomack,VA,0.2858
2,2020,Social and Community Context,Social Vulnerability Index (SVI),51001090202,Census Tract 902.02,Accomack,VA,0.5158
3,2020,Social and Community Context,Social Vulnerability Index (SVI),51001090300,Census Tract 903,Accomack,VA,0.6387
4,2020,Social and Community Context,Social Vulnerability Index (SVI),51001090401,Census Tract 904.01,Accomack,VA,0.8315
...,...,...,...,...,...,...,...,...
2180,2020,Social and Community Context,Social Vulnerability Index (SVI),51840000102,Census Tract 1.02,Winchester City,VA,0.9573
2181,2020,Social and Community Context,Social Vulnerability Index (SVI),51840000201,Census Tract 2.01,Winchester City,VA,0.6220
2182,2020,Social and Community Context,Social Vulnerability Index (SVI),51840000202,Census Tract 2.02,Winchester City,VA,0.2283
2183,2020,Social and Community Context,Social Vulnerability Index (SVI),51840000301,Census Tract 3.01,Winchester City,VA,0.8226
2184,2020,Social and Community Context,Social Vulnerability Index (SVI),51840000302,Census Tract 3.02,Winchester City,VA,0.7642

#### Calculating the mean Social Vulnerability Index and percentage on preventative services for each county

In [ ]:
# summarizing the variables by county and calculating their median values
hcaq_summary, csvi_summary = (
    hc_access_quality.groupby("County")["SV_index"].median(),
    context_svi.groupby("County")["pct_services"].median()
)

# printing dataframe summary
print(hcaq_summary)
print(csvi_summary)

County
Accomack             45.299997
Albemarle            48.614217
Alexandria City      46.375000
Alleghany            40.700165
Amelia               45.250000
                       ...
Williamsburg City    44.374390
Winchester City      43.005964
Wise                 43.062729
Wythe                41.175026
York                 49.488776
Name: SV_index, Length: 133, dtype: float64
County
Accomack             0.65235
Albemarle            0.28480
Alexandria City      0.25075
Alleghany            0.38075
Amelia               0.55370
                      ...
Williamsburg City    0.47960
Winchester City      0.79340
Wise                 0.63620
Wythe                0.43195
York                 0.23050
Name: pct_services, Length: 133, dtype: float64

#### Counting and printing select counties based on queries

In [ ]:
# merging both datasets using the common GEOID column
merged_df = pd.merge(hc_access_quality, context_svi, on="GEOID", how="inner")

# counting and printing the number of census tracts that have an svi greater than 0.5 and/or the percentage on preventative services
# is less than 45%
count = ((merged_df["SV_index"] > 0.5) | (merged_df["pct_services"] < 45)).sum()
print(count)

# counting and printing the number of census tracts that have an svi less than 0.6 and a percentage on preventative services of more
# than 70%
count = ((merged_df["SV_index"] < 0.6) & (merged_df["pct_services"] > 70)).sum()
print(count)

2174
0

#### Categorizing the census tracts into quartiles based on percentage of total population with higher education

In [ ]:
# installing and importing the census library
!pip install census
from census import Census

# setting API key
API_KEY = "955580bc8f3a7fc9a503d1f66f6c6ddd2b0db1a4"
c = Census(API_KEY, year=2022)

# listing the variables for total population, population with regular high school diploma, population with Bachelor's degree,
# population with master's degree, and population with doctorate degree
variables = ["B01003_001E", "B15003_017E", "B15003_022E", "B15003_023E", "B15003_025E"]

# calling the API for all census tracts in Pennsylvania
pa_acs = c.acs5.get(
    tuple(variables),
    {
        "for": "tract:*",
        "in": "state:42"
    }
)

# loading into a pandas dataframe
import pandas as pd
pa_df = pd.DataFrame(pa_acs)

Collecting census
  Downloading census-0.8.27-py3-none-any.whl.metadata (8.2 kB)
Requirement already satisfied: requests>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from census) (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=1.1.0->census) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=1.1.0->census) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=1.1.0->census) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=1.1.0->census) (2026.5.20)
Downloading census-0.8.27-py3-none-any.whl (11 kB)
Installing collected packages: census
Successfully installed census-0.8.27

In [ ]:
import requests

# The base URL for the Census API
census_api_host = 'https://api.census.gov'

try:
    response = requests.get(census_api_host, timeout=5)
    response.raise_for_status()
    print(f"Successfully connected to {census_api_host}. Status Code: {response.status_code}")
except requests.exceptions.ConnectionError as e:
    print(f"Could not connect to {census_api_host}. Connection error: {e}")
except requests.exceptions.Timeout:
    print(f"Could not connect to {census_api_host}. Request timed out after 5 seconds.")
except requests.exceptions.RequestException as e:
    print(f"An error occurred while connecting to {census_api_host}: {e}")

Successfully connected to https://api.census.gov. Status Code: 200

In [ ]:
# converting the list of dictionaries from the API call to a DataFrame
pa_df = pd.DataFrame(pa_acs)

# renaming variables for clarity
pa_df = pa_df.rename(columns={
    "B01003_001E": "total_pop",
    "B15003_017E": "hs_diploma_pop",
    "B15003_022E": "bachelors_pop",
    "B15003_023E": "masters_pop",
    "B15003_025E": "doctorate_pop"
})

# calculating total population with higher education by adding the relevant columns
pa_df["total_higher_education"] = (
    pa_df["bachelors_pop"] +
    pa_df["masters_pop"] +
    pa_df["doctorate_pop"]
)

# calculating percentage of total population with higher education
pa_df["pct_higher_education"] = (
    pa_df["total_higher_education"] / pa_df["total_pop"]
) * 100

# estimiating the quartile values for the percentage of total population with higher education
quartiles = pa_df["pct_higher_education"].quantile([0.25, 0.50, 0.75])

# creating a new column to categorize the census tracts into 1st-4th quartiles
pa_df["education_quartile"] = pd.cut(
    pa_df["pct_higher_education"],
    bins=[-float("inf"), quartiles[0.25], quartiles[0.5], quartiles[0.75], float("inf")],
    labels=[
        "1st Quartile (Lowest 25%)",
        "2nd Quartile (25%-50%)",
        "3rd Quartile (50%-75%)",
        "4th Quartile (Highest 25%)"
    ]
)

In [ ]:
display(pa_df['education_quartile'].value_counts())

education_quartile
1st Quartile (Lowest 25%)     854
4th Quartile (Highest 25%)    854
2nd Quartile (25%-50%)        853
3rd Quartile (50%-75%)        853
Name: count, dtype: int64

#### Calculating the average block group area for each county in Pennsylvania

In [ ]:
# importing Pennsylvania block groups from TIGER/Line Shapefiles
from google.colab import files
uploaded = files.upload()

Saving tl_2025_42_bg.zip to tl_2025_42_bg.zip

In [ ]:
# importing pandas
import geopandas as gpd

# importing shapefile
pa_tract = gpd.read_file('tl_2025_42_bg.zip')

# checking the crs of the shapefile
pa_tract.crs

# converting the crs to 3857 and assigning it back
pa_tract = pa_tract.to_crs(epsg = 3857)

# printing the differences in the geometries
print("The coordinate units are now in meters instead of degrees")

# calculating and printing the number of unique counties
num_unique = pa_tract['COUNTYFP'].nunique()
print("Number of unique counties:", num_unique)

# calculating average block group area for each county
pa_tract["area_sqm"] = pa_tract.geometry.area
avg_area = pa_tract.groupby("COUNTYFP")["area_sqm"].mean().reset_index()

# printing average block group area for each county
print("Average block group area for each county", avg_area)

The coordinate units are now in meters instead of degrees
Number of unique counties: 67
Average block group area for each county    COUNTYFP      area_sqm
0       001  3.377645e+07
1       003  3.139557e+06
2       005  4.553123e+07
3       007  1.461186e+07
4       009  1.069789e+08
..      ...           ...
62      125  2.210979e+07
63      127  7.113082e+07
64      129  1.743157e+07
65      131  8.511608e+07
66      133  1.187864e+07

[67 rows x 2 columns]